  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/microservice_db
      username: postgres
      password: 22817
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
